"""Static HTML snapshot export, for publishing to GitHub Pages (or anywhere
else static). This is NOT a live view — it's a point-in-time render of the
current DB state, regenerated by re-running `pool export-html` and
committing the output.

Privacy default: individual field-entry names and points are NOT included
in the export (only aggregate counts) unless include_field_names=True is
passed, since the field standings otherwise include ~100+ other people's
names on what would be a public URL.
"""
from __future__ import annotations

import html
import sqlite3
from datetime import datetime, timezone
from typing import List, Optional

from .config import PoolConfig
from .queries import compute_field_reconstruction, compute_my_entry_timeline
from .recommend import build_weekly_recommendations
from .simulation import EntryPolicy, SimAssumptions, run_simulation

_STYLE = """
body{margin:0;background:#0f2818;color:#eef2ea;font-family:'Space Grotesk',system-ui,sans-serif;padding:28px 20px 60px;}
.mono{font-family:'IBM Plex Mono',monospace;}
h1{font-size:22px;margin:0 0 4px;}
h2{font-size:17px;color:#e8a33d;margin:32px 0 10px;}
.sub{color:#a9bfae;font-size:13px;margin:0 0 20px;}
.card{background:#173a24;border:1px solid #2a4d34;border-radius:6px;padding:16px 20px;margin-bottom:16px;max-width:900px;}
table{width:100%;border-collapse:collapse;font-size:12.5px;}
th{text-align:left;color:#a9bfae;font-weight:500;font-size:11px;padding:6px 8px;border-bottom:1px solid #2a4d34;}
td{padding:6px 8px;border-bottom:1px solid rgba(255,255,255,.04);}
.pos{color:#7ec98f;} .neg{color:#c9564a;}
.note{font-size:12px;color:#a9bfae;line-height:1.5;margin-top:8px;}
.warn{color:#e8a33d;}
"""


def _esc(s) -> str:
    return html.escape(str(s))


def _entries(conn: sqlite3.Connection) -> List[sqlite3.Row]:
    return conn.execute(
        "SELECT id, display_name FROM entry WHERE is_mine = 1 ORDER BY display_name"
    ).fetchall()


def _timeline_section(conn: sqlite3.Connection, cfg: PoolConfig) -> str:
    parts = ["<h2>My entries</h2>"]
    for e in _entries(conn):
        tl = compute_my_entry_timeline(conn, e["id"], cfg)
        elim_tag = ' <span class="neg">(eliminated)</span>' if tl.eliminated else ""
        parts.append(
            f'<div class="card"><b>{_esc(e["display_name"])}</b> — '
            f'<span class="mono">{tl.current_points:g} pts</span>{elim_tag}'
        )
        if tl.rows:
            parts.append(
                "<table><thead><tr><th>Wk</th><th>Game</th><th>Side</th>"
                "<th>Pick</th><th>Bet</th><th>Result</th></tr></thead><tbody>"
            )
            for r in tl.rows:
                after = f"{r.points_after:g}" if r.points_after is not None else "pending"
                cls = "pos" if (r.result and r.result.delta >= 0) else ("neg" if r.result else "")
                parts.append(
                    f"<tr><td>{r.week_number}</td><td class='mono'>{_esc(r.away_team)}@{_esc(r.home_team)}</td>"
                    f"<td>{_esc(r.assigned_side)}</td><td>{_esc(r.pick or '—')}</td>"
                    f"<td class='mono'>{r.bet if r.bet is not None else '—'}</td>"
                    f"<td class='mono {cls}'>{after}</td></tr>"
                )
            parts.append("</tbody></table>")
        else:
            parts.append('<div class="note">No weeks logged yet.</div>')
        parts.append("</div>")
    return "".join(parts)


def _recommendations_section(
    conn: sqlite3.Connection, cfg: PoolConfig, season: Optional[int], week: Optional[int]
) -> str:
    if season is None or week is None:
        return ""
    entries = _entries(conn)
    entry_inputs = []
    for e in entries:
        assignment = conn.execute(
            """
            SELECT g.away_team, g.home_team, g.favorite, g.spread_margin, a.assigned_side
            FROM assignment a JOIN game g ON g.id = a.game_id
            WHERE a.entry_id = ? AND g.week_id = (
                SELECT id FROM week WHERE season_year = ? AND week_number = ?
            )
            """,
            (e["id"], season, week),
        ).fetchone()
        if assignment is None:
            continue
        tl = compute_my_entry_timeline(conn, e["id"], cfg)
        side = assignment["assigned_side"]
        favorite, margin = assignment["favorite"], assignment["spread_margin"] or 0
        spread = margin if favorite != side else -margin
        entry_inputs.append(
            {
                "name": e["display_name"],
                "current_points": tl.current_points,
                "is_upset_opportunity": abs(spread) >= cfg.upset_spread_threshold,
                "away": assignment["away_team"],
                "home": assignment["home_team"],
                "side": side,
                "spread": spread,
            }
        )
    if not entry_inputs:
        return (
            f'<h2>Week {week} recommendations</h2><div class="card note">'
            f"No assignments logged for week {week} yet.</div>"
        )

    field_count_row = conn.execute(
        """
        SELECT COUNT(DISTINCT entry_id) AS n FROM entry_week_points ewp
        JOIN week w ON w.id = ewp.week_id WHERE w.season_year = ?
        """,
        (season,),
    ).fetchone()
    field_size = max(field_count_row["n"] or 0, cfg.default_field_size)
    assumptions = SimAssumptions(
        weeks_remaining=max(1, 18 - week),
        field_size=field_size,
        runs=1500,
        min_bet=cfg.min_bet,
        start_points=cfg.start_points,
    )
    recs = build_weekly_recommendations(entry_inputs, assumptions, cfg.payouts, cfg.entry_fee, seed=1)

    parts = [f"<h2>Week {week} recommendations</h2>"]
    for e, rec in zip(entry_inputs, recs):
        s = rec.sim_result
        parts.append(
            f'<div class="card"><b>{_esc(rec.entry_name)}</b> — '
            f"{_esc(e['away'])} @ {_esc(e['home'])} (you: {_esc(e['side'])}), spread {e['spread']:g}"
            f"<div class='note'>Current points: {rec.current_points:g}</div>"
            f"<div class='note'>Recommended bet: <b class='mono'>{rec.recommended_bet:g}</b></div>"
            f"<div class='note'>{_esc(rec.recommended_pick_reasoning)}</div>"
            f"<div class='note'>Simulated: P(1st)={s.p_first:.1%} · P(top3)={s.p_top3:.1%} · "
            f"P(top10)={s.p_top10:.1%} · Expected payout=${s.avg_payout_dollars:.2f}</div></div>"
        )
    return "".join(parts)


def _scenario_section(conn: sqlite3.Connection, cfg: PoolConfig, season: Optional[int], week: Optional[int]) -> str:
    entries = _entries(conn)
    if not entries:
        return ""
    weeks_remaining = max(1, 18 - (week or 1))
    field_size = cfg.default_field_size

    scenarios = [
        ("Conservative (20% / no upset-taking)", 0.20, False),
        ("Moderate (30% / take upsets)", 0.30, True),
        ("Aggressive (45% / take upsets)", 0.45, True),
        ("All-in on upsets (60% / take upsets)", 0.60, True),
    ]
    # Fewer runs than the single-policy simulation elsewhere: this section runs
    # 4 full simulations back to back, and the output is already framed as
    # directional/approximate, not precise.
    assumptions = SimAssumptions(
        weeks_remaining=weeks_remaining, field_size=field_size, runs=400, min_bet=cfg.min_bet,
        start_points=cfg.start_points,
    )

    starts = []
    for e in entries:
        tl = compute_my_entry_timeline(conn, e["id"], cfg)
        starts.append(tl.current_points)

    parts = [
        "<h2>Scenario lab</h2>",
        '<div class="card note">Same field-behavior assumptions, different bet-sizing policy for '
        f"your entries — {weeks_remaining} weeks remaining, modeled field size {field_size}. "
        "Directional, not precise (see note at the bottom).</div>",
    ]
    for label, frac, take_upset in scenarios:
        policies = [EntryPolicy(bet_fraction=frac, take_upset=take_upset) for _ in entries]
        results = run_simulation(assumptions, policies, starts, cfg.payouts, cfg.entry_fee, seed=1)
        parts.append(f'<div class="card"><b>{_esc(label)}</b><table><thead><tr><th>Entry</th>'
                     "<th>P(1st)</th><th>P(top3)</th><th>P(top10)</th><th>Expected payout</th></tr></thead><tbody>")
        for e, r in zip(entries, results):
            parts.append(
                f"<tr><td>{_esc(e['display_name'])}</td><td class='mono'>{r.p_first:.1%}</td>"
                f"<td class='mono'>{r.p_top3:.1%}</td><td class='mono'>{r.p_top10:.1%}</td>"
                f"<td class='mono'>${r.avg_payout_dollars:.2f}</td></tr>"
            )
        parts.append("</tbody></table></div>")
    return "".join(parts)


def _field_summary_section(
    conn: sqlite3.Connection,
    cfg: PoolConfig,
    season: Optional[int],
    week: Optional[int],
    include_field_names: bool,
) -> str:
    if season is None or week is None:
        return ""
    if include_field_names:
        rows = compute_field_reconstruction(conn, season, week, cfg)
        if not rows:
            return f'<h2>Field — week {week}</h2><div class="card note">No field data for week {week}.</div>'
        parts = [
            f"<h2>Field — week {week}</h2>",
            '<div class="card"><table><thead><tr><th>Entry</th><th>Game</th>'
            "<th>Prev</th><th>Cur</th><th>Δ</th><th>Likely bet</th></tr></thead><tbody>",
        ]
        for r in rows:
            cands = ", ".join(f"{c.pick} {c.bet}" for c in r.candidates) or "—"
            parts.append(
                f"<tr><td>{_esc(r.entry_name)}</td><td class='mono'>{_esc(r.away_team)}@{_esc(r.home_team)}</td>"
                f"<td class='mono'>{r.prev_points if r.prev_points is not None else '—'}</td>"
                f"<td class='mono'>{r.current_points if r.current_points is not None else '—'}</td>"
                f"<td class='mono'>{r.delta if r.delta is not None else '—'}</td><td>{_esc(cands)}</td></tr>"
            )
        parts.append("</tbody></table></div>")
        return "".join(parts)

    week_row = conn.execute(
        "SELECT id FROM week WHERE season_year = ? AND week_number = ?", (season, week)
    ).fetchone()
    if week_row is None:
        return ""
    total = conn.execute(
        "SELECT COUNT(*) AS n FROM entry_week_points WHERE week_id = ?", (week_row["id"],)
    ).fetchone()["n"]
    eliminated = conn.execute(
        "SELECT COUNT(*) AS n FROM entry_week_points WHERE week_id = ? AND points <= 0",
        (week_row["id"],),
    ).fetchone()["n"]
    return (
        f"<h2>Field — week {week} (aggregate only)</h2>"
        f'<div class="card note">{total} entries tracked, {eliminated} eliminated. '
        "Individual field-entry names/points are omitted from this export by default "
        "(this page is published to a public URL) — rerun with --include-field-names "
        "to include the full per-entry breakdown.</div>"
    )


def render_report_html(
    conn: sqlite3.Connection,
    cfg: PoolConfig,
    *,
    season: Optional[int] = None,
    week: Optional[int] = None,
    include_field_names: bool = True,
) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    label = f"Season {season}, week {week}" if season and week else "No active week set"

    body = "".join(
        [
            "<h1>Office-Pool-4-Fun — Strategy Console</h1>",
            f'<p class="sub">Static snapshot · {label} · generated {generated_at} · '
            "not live — rerun `pool export-html` and push to refresh.</p>",
            _timeline_section(conn, cfg),
            _recommendations_section(conn, cfg, season, week),
            _scenario_section(conn, cfg, season, week),
            _field_summary_section(conn, cfg, season, week, include_field_names),
            '<h2>Open assumptions</h2><div class="card note">'
            f"Upset-direction rule (favorite-LOSS counts as a qualifying 10x upset): "
            f"currently assumed <b>{'yes' if cfg.upset_counts_favorite_loss else 'no'}</b> "
            f"(config-driven, unconfirmed against a settled week). Spread source for "
            f"10x qualification: <b>{_esc(cfg.spread_source_name)}</b>.</div>",
        ]
    )

    return (
        "<!doctype html><html lang='en'><head><meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        "<title>Office-Pool-4-Fun — Strategy Console</title>"
        f"<style>{_STYLE}</style></head><body>{body}</body></html>"
    )
