"""Static HTML snapshot export, for publishing to GitHub Pages (or anywhere
else static). This is NOT a live view — it's a point-in-time render of the
current DB state, regenerated by re-running `pool export-html` and
committing the output.

Privacy default: individual field-entry names and points ARE included by
default (--no-field-names to reduce to aggregate counts), since the field
standings are otherwise public info on a public-by-default GitHub Pages URL.

Visual design: a single deliberate "under the lights" dark world — a night
game's turf and an amber odds-board glow — rather than a light/dark toggle.
That's a one-time choice for a personal scoreboard page, not an oversight.
"""
from __future__ import annotations

import html
import json
import sqlite3
from datetime import datetime, timezone
from typing import List, Optional

from .config import PoolConfig
from .queries import (
    compute_field_reconstruction,
    compute_my_entry_timeline,
    get_scenario_projection_data,
)
from .recommend import build_weekly_recommendations
from .simulation import EntryPolicy, SimAssumptions, run_simulation

_STYLE = """
:root{
  --turf:#0a1f16; --turf-raised:#12291d; --turf-raised-2:#183422;
  --line:#28492f; --chalk:#eef2ea; --chalk-dim:#9db6a5;
  --amber:#f2a33d; --amber-dim:#c9822c;
  --win:#6fcf8e; --loss:#e2645a; --push:#6ea8d8;
}
*{box-sizing:border-box;}
body{margin:0; background:var(--turf); color:var(--chalk); font-family:'Public Sans',system-ui,-apple-system,sans-serif;}
#app{display:flex; min-height:100vh;}
nav{
  width:224px; flex-shrink:0; background:var(--turf-raised);
  border-right:1px solid var(--line); padding:26px 0; display:flex; flex-direction:column;
}
.brand{padding:0 20px 18px; border-bottom:1px solid var(--line); margin-bottom:8px;}
.brand-title{font-family:'Big Shoulders Display',sans-serif; font-weight:800; font-size:21px; margin:0; line-height:1.15;}
.tab-btn{
  text-align:left; background:none; border:none; color:var(--chalk-dim);
  padding:12px 20px; font-size:14px; cursor:pointer; font-family:'Public Sans',sans-serif;
  border-left:3px solid transparent; width:100%;
}
.tab-btn:hover{color:var(--chalk); background:rgba(255,255,255,.03);}
.tab-btn.active{color:var(--amber); border-left-color:var(--amber); background:rgba(242,163,61,.06); font-weight:600;}
.nav-foot{margin-top:auto; padding:16px 20px 0; border-top:1px solid var(--line);}
main{flex:1; min-width:0; padding:36px 40px 70px; max-width:960px;}
[data-tabcontent][hidden]{display:none;}
.mono{font-family:'IBM Plex Mono',ui-monospace,monospace; font-variant-numeric:tabular-nums;}
.eyebrow{
  font-family:'IBM Plex Mono',monospace; font-size:11px; letter-spacing:.14em;
  color:var(--amber); text-transform:uppercase; margin:0 0 8px;
}
h1{
  font-family:'Big Shoulders Display',sans-serif; font-weight:800;
  font-size:34px; line-height:1; margin:0 0 6px; text-wrap:balance;
  letter-spacing:.01em;
}
h2{
  font-family:'Big Shoulders Display',sans-serif; font-weight:700;
  font-size:22px; color:var(--chalk); margin:0 0 12px;
  border-bottom:1px solid var(--line); padding-bottom:6px;
}
.meta{color:var(--chalk-dim); font-size:13px; margin:0 0 30px; font-family:'IBM Plex Mono',monospace;}
.scoreboard-strip{
  display:grid; grid-template-columns:repeat(auto-fit,minmax(220px,1fr));
  gap:12px; margin-bottom:36px;
}
.tile{
  background:var(--turf-raised); border:1px solid var(--line); border-radius:8px;
  padding:16px 18px; display:flex; flex-direction:column; gap:6px;
}
.tile-label{font-size:13px; font-weight:600; margin:0; color:var(--chalk);}
.tile-points{
  font-family:'Big Shoulders Display',sans-serif; font-weight:800; font-size:44px;
  line-height:1; margin:0; color:var(--amber); font-variant-numeric:tabular-nums;
}
.tile-foot{display:flex; align-items:center; gap:8px; font-size:12px;}
.entry-section{margin-bottom:44px;}
.entry-section h2{display:flex; align-items:baseline; gap:10px;}
.entry-section h2 .pts{font-size:15px; color:var(--chalk-dim); font-weight:500; font-family:'IBM Plex Mono',monospace;}
.card{
  background:var(--turf-raised); border:1px solid var(--line); border-radius:8px;
  padding:16px 18px; margin-bottom:14px;
}
.card-title{font-size:11px; text-transform:uppercase; letter-spacing:.08em; color:var(--chalk-dim); margin:0 0 10px; font-weight:600;}
.table-scroll{overflow-x:auto;}
table{width:100%; border-collapse:collapse; font-size:13px;}
th{
  text-align:left; color:var(--chalk-dim); font-weight:600; font-size:10.5px;
  letter-spacing:.05em; text-transform:uppercase; padding:6px 10px 8px;
  border-bottom:1px solid var(--line); white-space:nowrap;
}
td{padding:8px 10px; border-bottom:1px solid rgba(255,255,255,.05); white-space:nowrap;}
tr:last-child td{border-bottom:none;}
.pos{color:var(--win);} .neg{color:var(--loss);}
.pill{
  display:inline-flex; align-items:center; gap:5px; padding:2px 9px;
  border-radius:20px; font-size:11px; font-weight:600; white-space:nowrap;
}
.pill-active{background:rgba(111,207,142,.14); color:var(--win);}
.pill-elim{background:rgba(226,100,90,.16); color:var(--loss);}
.pill-pending{background:rgba(255,255,255,.08); color:var(--chalk-dim);}
.badge-upset{
  display:inline-block; margin-left:6px; padding:1px 7px; border-radius:3px;
  background:rgba(242,163,61,.16); color:var(--amber); font-size:10px;
  font-weight:700; letter-spacing:.04em; text-transform:uppercase;
  font-family:'IBM Plex Mono',monospace;
}
.slip{display:grid; grid-template-columns:1fr 1fr; gap:0; align-items:stretch;}
.slip-half{padding:4px 0;}
.slip-divider{
  border-left:1px dashed var(--line); margin:0 20px; position:relative;
}
.slip-label{font-size:10.5px; text-transform:uppercase; letter-spacing:.07em; color:var(--chalk-dim); margin:0 0 4px;}
.slip-value{font-family:'IBM Plex Mono',monospace; font-size:20px; font-weight:600; color:var(--amber); margin:0 0 8px; font-variant-numeric:tabular-nums;}
.slip-reasoning{font-size:12.5px; color:var(--chalk-dim); line-height:1.55; margin:0;}
.sim-strip{display:flex; flex-wrap:wrap; gap:16px; margin-top:12px; padding-top:12px; border-top:1px solid var(--line);}
.sim-stat{display:flex; flex-direction:column; gap:2px;}
.sim-stat .n{font-family:'IBM Plex Mono',monospace; font-size:15px; font-weight:600; font-variant-numeric:tabular-nums;}
.sim-stat .l{font-size:10.5px; color:var(--chalk-dim); text-transform:uppercase; letter-spacing:.05em;}
.stat-row{display:flex; flex-wrap:wrap; gap:12px;}
.stat-tile{
  background:var(--turf-raised); border:1px solid var(--line); border-radius:8px;
  padding:14px 18px; flex:1; min-width:160px;
}
.stat-tile .n{font-family:'Big Shoulders Display',sans-serif; font-weight:800; font-size:28px; color:var(--amber);}
.stat-tile .l{font-size:12px; color:var(--chalk-dim); margin-top:2px;}
.empty-note{font-size:13px; color:var(--chalk-dim); font-style:italic;}
.scenario-row{
  display:flex; flex-wrap:wrap; align-items:center; gap:10px;
  padding:9px 0; border-bottom:1px solid rgba(255,255,255,.05);
}
.scenario-row:last-child{border-bottom:none;}
.scenario-row .game-label{font-family:'IBM Plex Mono',monospace; font-size:12.5px; min-width:190px;}
.scenario-row select, .scenario-row input[type=number]{
  background:var(--turf); border:1px solid var(--line); color:var(--chalk);
  border-radius:5px; padding:5px 8px; font-family:'IBM Plex Mono',monospace; font-size:12.5px;
}
.scenario-row input[type=range]{accent-color:var(--amber); flex:1; min-width:100px;}
.scenario-mine-card{
  background:var(--turf); border:1px solid var(--line); border-radius:6px;
  padding:10px 12px; display:flex; flex-wrap:wrap; align-items:center; gap:10px; margin-bottom:8px;
}
.scenario-mine-card .name{font-weight:600; min-width:70px;}
.scenario-mine-card label{font-size:10.5px; color:var(--chalk-dim); text-transform:uppercase; letter-spacing:.05em; margin-right:4px;}
.scenario-mine-card input[type=number]{width:80px;}
#scenarioTable tr.mine td{color:var(--amber); font-weight:600;}
#scenarioTable tr.mine td:first-child, #scenarioTable tr.mine td:nth-child(2){color:var(--chalk);}
#scenarioTable tr.mine td.mono{color:var(--amber);}
footer{
  margin-top:50px; padding-top:20px; border-top:1px dashed var(--line);
  font-family:'IBM Plex Mono',monospace; font-size:11.5px; color:var(--chalk-dim); line-height:1.7;
}
footer b{color:var(--chalk);}
@media (max-width:760px){
  #app{flex-direction:column;}
  nav{
    width:100%; flex-direction:row; align-items:center; padding:12px;
    border-right:none; border-bottom:1px solid var(--line); overflow-x:auto;
  }
  .brand{border-bottom:none; border-right:1px solid var(--line); padding:0 14px 0 0; margin:0 6px 0 0; flex-shrink:0;}
  .tab-btn{border-left:none; border-bottom:3px solid transparent; padding:8px 14px; width:auto; white-space:nowrap;}
  .tab-btn.active{border-left-color:transparent; border-bottom-color:var(--amber);}
  .nav-foot{display:none;}
  main{padding:22px 18px 50px;}
}
@media (max-width:520px){
  .slip{grid-template-columns:1fr;}
  .slip-divider{border-left:none; border-top:1px dashed var(--line); margin:10px 0;}
  h1{font-size:28px;}
}
"""


def _esc(s) -> str:
    return html.escape(str(s))


def _entries(conn: sqlite3.Connection) -> List[sqlite3.Row]:
    return conn.execute(
        "SELECT id, display_name FROM entry WHERE is_mine = 1 ORDER BY display_name"
    ).fetchall()


def _spread_label(spread: float, threshold: float) -> str:
    if spread == 0:
        text = "pick&rsquo;em"
    elif spread > 0:
        text = f"+{spread:g} <span style='color:var(--chalk-dim)'>(dog)</span>"
    else:
        text = f"&minus;{abs(spread):g} <span style='color:var(--chalk-dim)'>(fav)</span>"
    if abs(spread) >= threshold:
        text += '<span class="badge-upset">Upset line</span>'
    return text


def _scoreboard_strip(timelines: dict) -> str:
    tiles = []
    for name, tl in timelines.items():
        if tl.eliminated:
            pill = '<span class="pill pill-elim">Eliminated</span>'
        elif tl.rows:
            pill = '<span class="pill pill-active">Active</span>'
        else:
            pill = '<span class="pill pill-pending">Not started</span>'
        last = ""
        if tl.rows and tl.rows[-1].result is not None:
            r, res = tl.rows[-1], tl.rows[-1].result
            cls = "pos" if res.delta >= 0 else "neg"
            sign = "+" if res.delta >= 0 else ""
            last = f'<span class="mono {cls}">wk{r.week_number} {sign}{res.delta:g}</span>'
        tiles.append(
            f'<div class="tile"><p class="tile-label">{_esc(name)}</p>'
            f'<p class="tile-points">{tl.current_points:g}</p>'
            f'<div class="tile-foot">{pill}{last}</div></div>'
        )
    return f'<div class="scoreboard-strip">{"".join(tiles)}</div>'


def _log_table(tl) -> str:
    if not tl.rows:
        return '<p class="empty-note">No weeks logged yet.</p>'
    rows = []
    for r in tl.rows:
        if r.result is None:
            status = '<span class="pill pill-pending">Pending</span>'
            after_cls = ""
        elif r.pick == "TIE" and r.result.mult > 1:
            status = '<span class="pill" style="background:rgba(110,168,216,.16);color:var(--push)">Tie 10&times;</span>'
            after_cls = "pos"
        elif r.result.delta >= 0:
            status = '<span class="pill pill-active">Win</span>' + (
                ' <span class="badge-upset">10&times;</span>' if r.result.mult > 1 else ""
            )
            after_cls = "pos"
        else:
            status = '<span class="pill pill-elim">Loss</span>'
            after_cls = "neg"
        after = f"{r.points_after:g}" if r.points_after is not None else "&mdash;"
        bet = f"{r.bet:g}" if r.bet is not None else "&mdash;"
        pick = _esc(r.pick) if r.pick else "&mdash;"
        rows.append(
            f"<tr><td>{r.week_number}</td>"
            f"<td class='mono'>{_esc(r.away_team)} @ {_esc(r.home_team)}</td>"
            f"<td>{_esc(r.assigned_side)}</td><td>{pick}</td>"
            f"<td class='mono'>{bet}</td>"
            f"<td>{status}</td><td class='mono {after_cls}'>{after}</td></tr>"
        )
    return (
        '<div class="table-scroll"><table><thead><tr><th>Wk</th><th>Game</th><th>Side</th>'
        "<th>Pick</th><th>Bet</th><th>Result</th><th>Points</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div>"
    )


def _entry_assignment(conn, entry_id, season, week):
    return conn.execute(
        """
        SELECT g.away_team, g.home_team, g.favorite, g.spread_margin, a.assigned_side
        FROM assignment a JOIN game g ON g.id = a.game_id
        WHERE a.entry_id = ? AND g.week_id = (
            SELECT id FROM week WHERE season_year = ? AND week_number = ?
        )
        """,
        (entry_id, season, week),
    ).fetchone()


def _recommendation_slip(rec, e, cfg) -> str:
    s = rec.sim_result
    spread_html = _spread_label(e["spread"], cfg.upset_spread_threshold)
    return (
        '<div class="card"><p class="card-title">This week&rsquo;s pick</p>'
        '<div class="slip">'
        '<div class="slip-half">'
        f'<p class="slip-label">{_esc(e["away"])} @ {_esc(e["home"])} &middot; you: {_esc(e["side"])}</p>'
        f'<p class="slip-value">{spread_html}</p>'
        f'<p class="slip-reasoning">Current stack: <b class="mono">{rec.current_points:g}</b> pts</p>'
        "</div>"
        '<div class="slip-divider"></div>'
        '<div class="slip-half">'
        '<p class="slip-label">Recommended stake</p>'
        f'<p class="slip-value">{rec.recommended_bet:g} pts</p>'
        f'<p class="slip-reasoning">{_esc(rec.recommended_pick_reasoning)}</p>'
        "</div></div>"
        '<div class="sim-strip">'
        f'<div class="sim-stat"><span class="n">{s.p_first:.1%}</span><span class="l">P(1st)</span></div>'
        f'<div class="sim-stat"><span class="n">{s.p_top3:.1%}</span><span class="l">P(top 3)</span></div>'
        f'<div class="sim-stat"><span class="n">{s.p_top10:.1%}</span><span class="l">P(top 10)</span></div>'
        f'<div class="sim-stat"><span class="n">${s.avg_payout_dollars:.2f}</span><span class="l">Expected payout</span></div>'
        "</div></div>"
    )


def _scenario_table(conn, cfg, entry_id, start_points, weeks_remaining, field_size) -> str:
    scenarios = [
        ("Conservative", "20% &middot; hold on upsets", 0.20, False),
        ("Moderate", "30% &middot; take upsets", 0.30, True),
        ("Aggressive", "45% &middot; take upsets", 0.45, True),
        ("All-in on upsets", "60% &middot; take upsets", 0.60, True),
    ]
    assumptions = SimAssumptions(
        weeks_remaining=weeks_remaining, field_size=field_size, runs=400,
        min_bet=cfg.min_bet, start_points=cfg.start_points,
    )
    rows = []
    for label, sub, frac, take_upset in scenarios:
        result = run_simulation(
            assumptions, [EntryPolicy(bet_fraction=frac, take_upset=take_upset)],
            [start_points], cfg.payouts, cfg.entry_fee, seed=1,
        )[0]
        rows.append(
            f"<tr><td><b>{_esc(label)}</b><br><span style='color:var(--chalk-dim);font-size:11px'>{sub}</span></td>"
            f"<td class='mono'>{result.p_first:.1%}</td><td class='mono'>{result.p_top3:.1%}</td>"
            f"<td class='mono'>{result.p_top10:.1%}</td><td class='mono'>${result.avg_payout_dollars:.2f}</td></tr>"
        )
    return (
        '<div class="card"><p class="card-title">Scenario lab &mdash; '
        f"{weeks_remaining} weeks remaining, modeled field {field_size}</p>"
        '<div class="table-scroll"><table><thead><tr><th>Policy</th><th>P(1st)</th>'
        f"<th>P(top 3)</th><th>P(top 10)</th><th>Expected payout</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div></div>"
    )


def _field_size_and_weeks_remaining(conn, cfg, season, week):
    field_count_row = conn.execute(
        """
        SELECT COUNT(DISTINCT entry_id) AS n FROM entry_week_points ewp
        JOIN week w ON w.id = ewp.week_id WHERE w.season_year = ?
        """,
        (season,),
    ).fetchone() if season else None
    field_size = max((field_count_row["n"] or 0) if field_count_row else 0, cfg.default_field_size)
    weeks_remaining = max(1, 18 - (week or 1))
    return field_size, weeks_remaining


def _entry_sections(
    conn: sqlite3.Connection, cfg: PoolConfig, season: Optional[int], week: Optional[int]
) -> tuple[str, dict]:
    """'My Entries' tab: game log + this week's pick, one block per entry.
    The Monte Carlo scenario comparison lives in its own Simulation tab
    now (see _simulation_tab_content) rather than repeated per entry here.
    """
    entries = _entries(conn)
    timelines = {}
    field_size, weeks_remaining = _field_size_and_weeks_remaining(conn, cfg, season, week)

    blocks = []
    for e in entries:
        tl = compute_my_entry_timeline(conn, e["id"], cfg)
        timelines[e["display_name"]] = tl

        section = [f'<section class="entry-section"><h2>{_esc(e["display_name"])} '
                   f'<span class="pts">{tl.current_points:g} pts</span></h2>']
        section.append(f'<div class="card"><p class="card-title">Game log</p>{_log_table(tl)}</div>')

        if season is not None and week is not None:
            assignment = _entry_assignment(conn, e["id"], season, week)
            if assignment is not None:
                side = assignment["assigned_side"]
                favorite, margin = assignment["favorite"], assignment["spread_margin"] or 0
                spread = margin if favorite != side else -margin
                entry_input = {
                    "name": e["display_name"], "current_points": tl.current_points,
                    "is_upset_opportunity": abs(spread) >= cfg.upset_spread_threshold,
                    "away": assignment["away_team"], "home": assignment["home_team"],
                    "side": side, "spread": spread,
                }
                assumptions = SimAssumptions(
                    weeks_remaining=weeks_remaining, field_size=field_size, runs=1500,
                    min_bet=cfg.min_bet, start_points=cfg.start_points,
                )
                rec = build_weekly_recommendations(
                    [entry_input], assumptions, cfg.payouts, cfg.entry_fee, seed=1
                )[0]
                section.append(_recommendation_slip(rec, entry_input, cfg))
            else:
                section.append(
                    f'<div class="card"><p class="card-title">This week&rsquo;s pick</p>'
                    f'<p class="empty-note">No assignment logged for week {week} yet.</p></div>'
                )
        section.append("</section>")
        blocks.append("".join(section))

    return "".join(blocks), timelines


def _simulation_tab_content(
    conn: sqlite3.Connection, cfg: PoolConfig, season: Optional[int], week: Optional[int]
) -> str:
    """Simulation tab: the Monte Carlo scenario-lab comparison for all 3
    entries together, instead of scattered one-per-entry inside 'My Entries'.
    """
    entries = _entries(conn)
    if not entries:
        return '<p class="empty-note">No entries yet.</p>'
    field_size, weeks_remaining = _field_size_and_weeks_remaining(conn, cfg, season, week)

    blocks = []
    for e in entries:
        tl = compute_my_entry_timeline(conn, e["id"], cfg)
        blocks.append(
            f'<h3 style="font-size:15px;margin:0 0 8px;color:var(--chalk-dim)">{_esc(e["display_name"])}'
            f'<span class="mono" style="margin-left:8px">{tl.current_points:g} pts</span></h3>'
        )
        blocks.append(
            _scenario_table(conn, cfg, e["id"], tl.current_points, weeks_remaining, field_size)
        )
    return "".join(blocks)


def _scenario_projector_section(
    conn: sqlite3.Connection,
    cfg: PoolConfig,
    season: Optional[int],
    week: Optional[int],
    include_field_names: bool,
) -> str:
    """Client-side, entirely-in-browser 'what if' standings projector: pick
    an outcome per game and a generalized field bet %, see the whole real
    field's (and your own) projected standings recompute instantly. No
    server involved — the scoring engine below is a JS port of
    pool/scoring.py, evaluated against the JSON data embedded in the page.

    Respects include_field_names the same as the rest of the export: when
    False, only 'my' entries are embedded — the field's names/points are
    just as public here (baked into the page's JSON) as anywhere else on
    the page, so this can't be looser than that setting.
    """
    if season is None or week is None:
        return ""
    data = get_scenario_projection_data(conn, season, week, cfg)
    if not include_field_names:
        data.entries = [e for e in data.entries if e.is_mine]
        relevant_games = {(e.away_team, e.home_team) for e in data.entries}
        data.games = [g for g in data.games if (g.away_team, g.home_team) in relevant_games]
    if not data.entries:
        return ""

    payload = {
        "config": {
            "upsetThreshold": cfg.upset_spread_threshold,
            "upsetMultiplier": cfg.upset_multiplier,
            "tieMultiplier": cfg.tie_multiplier,
            "countsFavoriteLoss": cfg.upset_counts_favorite_loss,
            "minBet": cfg.min_bet,
        },
        "games": [
            {"away": g.away_team, "home": g.home_team, "favorite": g.favorite,
             "margin": g.margin, "outcome": g.outcome}
            for g in data.games
        ],
        "entries": [
            {"name": e.name, "mine": e.is_mine, "away": e.away_team, "home": e.home_team,
             "side": e.assigned_side, "points": e.points_entering_week}
            for e in data.entries
        ],
    }
    # Guard against a name containing "</script>" breaking out of the tag.
    payload_json = json.dumps(payload).replace("</", "<\\/")

    js = r"""
(function(){
  var raw = document.getElementById('scenario-data');
  if(!raw) return;
  var DATA = JSON.parse(raw.textContent);
  var cfg = DATA.config;

  function spreadForTeam(game, side){
    if(!game || !game.margin) return 0;
    return game.favorite===side ? -game.margin : game.margin;
  }
  function isUpsetPick(spread, pick){
    if(Math.abs(spread) < cfg.upsetThreshold) return false;
    if(spread>0 && pick==='WIN') return true;
    if(spread<0 && pick==='LOSS' && cfg.countsFavoriteLoss) return true;
    return false;
  }
  function outcomeForSide(selection, side){
    if(!selection) return null;
    if(selection==='tie') return 'TIE_REG';
    return selection===side ? 'WIN' : 'LOSS';
  }
  function scoreBet(spread, pick, bet, outcome){
    if(outcome==null) return 0;
    if(outcome==='TIE_REG') return pick==='TIE' ? bet*cfg.tieMultiplier : -bet;
    if(pick==='TIE') return -bet;
    if(pick!==outcome) return -bet;
    return bet*(isUpsetPick(spread,pick) ? cfg.upsetMultiplier : 1);
  }
  function clampBet(points, raw){
    var floor = Math.min(cfg.minBet, points);
    return Math.max(0, Math.min(points, Math.max(floor, Math.round(raw))));
  }

  var gamesById = {};
  DATA.games.forEach(function(g){ gamesById[g.away+'@'+g.home] = g; });

  var gamesBox = document.getElementById('scenarioGames');
  var mineBox = document.getElementById('scenarioMine');
  var fracInput = document.getElementById('fieldFrac');
  var fracLabel = document.getElementById('fieldFracLabel');
  var tbody = document.querySelector('#scenarioTable tbody');

  var gameSelects = {};
  DATA.games.forEach(function(g){
    var key = g.away+'@'+g.home;
    var row = document.createElement('div');
    row.className = 'scenario-row';
    var label = document.createElement('span');
    label.className = 'game-label';
    label.textContent = g.away+' @ '+g.home;
    var sel = document.createElement('select');
    [['','Not decided'], ['away', g.away+' wins'], ['home', g.home+' wins'], ['tie','Tied at regulation']]
      .forEach(function(opt){
        var o = document.createElement('option');
        o.value = opt[0]; o.textContent = opt[1];
        sel.appendChild(o);
      });
    if(g.outcome){ sel.value = g.outcome; }
    sel.addEventListener('change', recompute);
    gameSelects[key] = sel;
    row.appendChild(label); row.appendChild(sel);
    if(g.outcome){
      var tag = document.createElement('span');
      tag.className = 'badge-upset'; tag.textContent = 'settled';
      row.appendChild(tag);
    }
    gamesBox.appendChild(row);
  });

  var minePicks = {}, mineBets = {};
  DATA.entries.filter(function(e){ return e.mine; }).forEach(function(e){
    var card = document.createElement('div');
    card.className = 'scenario-mine-card';
    var name = document.createElement('span');
    name.className = 'name'; name.textContent = e.name;
    var pickLabel = document.createElement('label'); pickLabel.textContent = 'Pick';
    var pickSel = document.createElement('select');
    ['WIN','LOSS','TIE'].forEach(function(p){
      var o = document.createElement('option'); o.value = p; o.textContent = p;
      pickSel.appendChild(o);
    });
    pickSel.value = 'WIN';
    pickSel.addEventListener('change', recompute);
    var betLabel = document.createElement('label'); betLabel.textContent = 'Wager';
    var betInput = document.createElement('input');
    betInput.type = 'number'; betInput.min = 0; betInput.max = e.points;
    betInput.value = Math.max(Math.min(cfg.minBet, e.points), Math.round(e.points*0.2/10)*10);
    betInput.addEventListener('input', recompute);
    minePicks[e.name] = pickSel; mineBets[e.name] = betInput;
    card.appendChild(name);
    card.appendChild(pickLabel); card.appendChild(pickSel);
    card.appendChild(betLabel); card.appendChild(betInput);
    mineBox.appendChild(card);
  });

  function recompute(){
    var frac = +fracInput.value / 100;
    fracLabel.textContent = fracInput.value + '%';

    var results = DATA.entries.map(function(e){
      var key = e.away+'@'+e.home;
      var game = gamesById[key];
      var selection = gameSelects[key] ? gameSelects[key].value : (game.outcome || '');
      var outcome = outcomeForSide(selection, e.side);
      var spread = spreadForTeam(game, e.side);
      var projected = e.points;
      var pending = true;
      if(outcome != null){
        pending = false;
        var pick, bet;
        if(e.mine){
          pick = minePicks[e.name].value;
          bet = clampBet(e.points, +mineBets[e.name].value);
        } else {
          pick = 'WIN';
          bet = clampBet(e.points, e.points*frac);
        }
        projected = e.points + scoreBet(spread, pick, bet, outcome);
      }
      return {name:e.name, mine:e.mine, points:e.points, projected:projected, pending:pending};
    });
    results.sort(function(a,b){ return b.projected - a.projected; });

    tbody.innerHTML = '';
    results.forEach(function(r, i){
      var tr = document.createElement('tr');
      if(r.mine) tr.className = 'mine';
      var delta = r.projected - r.points;
      var deltaTxt = r.pending ? '—' : ((delta>=0?'+':'')+Math.round(delta));
      var deltaCls = r.pending ? '' : (delta>=0 ? 'pos' : 'neg');
      [String(i+1), r.name, String(r.points), String(Math.round(r.projected))].forEach(function(txt, ci){
        var td = document.createElement('td');
        td.textContent = txt;
        if(ci>=2) td.className = 'mono';
        tr.appendChild(td);
      });
      var deltaTd = document.createElement('td');
      deltaTd.className = 'mono ' + deltaCls;
      deltaTd.textContent = deltaTxt;
      tr.appendChild(deltaTd);
      tbody.appendChild(tr);
    });
  }

  fracInput.addEventListener('input', recompute);
  recompute();
})();
"""

    return (
        '<div class="card"><p class="card-title">Assumptions</p>'
        '<div id="scenarioGames"></div>'
        '<div class="scenario-row"><span class="game-label">Field bet % (of current stack)</span>'
        '<input type="range" id="fieldFrac" min="0" max="60" value="20">'
        '<span id="fieldFracLabel" class="mono">20%</span></div>'
        '<div id="scenarioMine" style="margin-top:10px"></div>'
        '<p class="empty-note" style="margin-top:8px">Field entries are assumed to bet WIN on their '
        "assigned team at the field % above; games left “Not decided” leave that entry "
        "unchanged. Spreads reflect whatever's currently recorded (fetch-spread/confirm-spread) "
        "— pick&rsquo;em if none is set yet. Entirely computed in your browser — nothing "
        "is sent anywhere.</p></div>"
        '<div class="card"><p class="card-title">Projected standings</p>'
        '<div class="table-scroll"><table id="scenarioTable"><thead><tr><th>#</th><th>Entry</th>'
        "<th>Entering</th><th>Projected</th><th>&Delta;</th></tr></thead><tbody></tbody></table></div>"
        "</div>"
        f'<script type="application/json" id="scenario-data">{payload_json}</script>'
        f"<script>{js}</script>"
    )


def _field_summary_section(
    conn: sqlite3.Connection,
    cfg: PoolConfig,
    season: Optional[int],
    week: Optional[int],
    include_field_names: bool,
) -> str:
    if season is None or week is None:
        return ""
    if include_field_names:
        rows = compute_field_reconstruction(conn, season, week, cfg)
        if not rows:
            return f'<p class="empty-note">No field data for week {week}.</p>'
        trs = []
        for r in rows:
            cands_raw = ", ".join(f"{c.pick} {c.bet}" for c in r.candidates)
            cands = _esc(cands_raw) if cands_raw else "&mdash;"
            trs.append(
                f"<tr><td>{_esc(r.entry_name)}</td><td class='mono'>{_esc(r.away_team)}@{_esc(r.home_team)}</td>"
                f"<td class='mono'>{r.prev_points if r.prev_points is not None else '&mdash;'}</td>"
                f"<td class='mono'>{r.current_points if r.current_points is not None else '&mdash;'}</td>"
                f"<td class='mono'>{r.delta if r.delta is not None else '&mdash;'}</td><td>{cands}</td></tr>"
            )
        return (
            '<div class="card">'
            '<div class="table-scroll"><table><thead><tr><th>Entry</th><th>Game</th>'
            f"<th>Prev</th><th>Cur</th><th>&Delta;</th><th>Likely bet</th></tr></thead>"
            f"<tbody>{''.join(trs)}</tbody></table></div></div>"
        )

    week_row = conn.execute(
        "SELECT id FROM week WHERE season_year = ? AND week_number = ?", (season, week)
    ).fetchone()
    if week_row is None:
        return ""
    total = conn.execute(
        "SELECT COUNT(*) AS n FROM entry_week_points WHERE week_id = ?", (week_row["id"],)
    ).fetchone()["n"]
    eliminated = conn.execute(
        "SELECT COUNT(*) AS n FROM entry_week_points WHERE week_id = ? AND points <= 0",
        (week_row["id"],),
    ).fetchone()["n"]
    return (
        '<div class="stat-row">'
        f'<div class="stat-tile"><div class="n">{total}</div><div class="l">Entries tracked</div></div>'
        f'<div class="stat-tile"><div class="n">{eliminated}</div><div class="l">Eliminated</div></div>'
        "</div>"
        '<p class="empty-note" style="margin-top:10px">Individual field-entry names/points omitted '
        "(--no-field-names) &mdash; rerun without that flag for the full per-entry breakdown.</p>"
    )


_TABS = [
    ("overview", "Overview"),
    ("entries", "My Entries"),
    ("field", "Field"),
    ("projector", "Scenario Projector"),
    ("simulation", "Simulation"),
]


def render_report_html(
    conn: sqlite3.Connection,
    cfg: PoolConfig,
    *,
    season: Optional[int] = None,
    week: Optional[int] = None,
    include_field_names: bool = True,
) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%b %d, %Y &middot; %H:%M UTC")
    week_label = f"Week {week}" if week else "No active week set"
    meta = f"Season {season} &middot; {week_label}" if season else week_label

    entry_blocks, timelines = _entry_sections(conn, cfg, season, week)
    scoreboard = _scoreboard_strip(timelines) if timelines else ""
    field_content = _field_summary_section(conn, cfg, season, week, include_field_names)
    projector_content = _scenario_projector_section(conn, cfg, season, week, include_field_names)
    simulation_content = _simulation_tab_content(conn, cfg, season, week)

    tab_bodies = {
        "overview": (
            "<h1>Overview</h1>"
            f'<p class="meta">{meta} &middot; generated {generated_at} &middot; static snapshot '
            "&mdash; rerun <code>pool export-html</code> and push to refresh</p>"
            + (scoreboard or '<p class="empty-note">No entries yet.</p>')
        ),
        "entries": f"<h1>My Entries</h1><p class=\"meta\">{meta}</p>" + (
            entry_blocks or '<p class="empty-note">No entries yet.</p>'
        ),
        "field": f"<h1>Field</h1><p class=\"meta\">{meta}</p>" + (
            field_content or '<p class="empty-note">No field data for this week.</p>'
        ),
        "projector": f"<h1>Scenario Projector</h1><p class=\"meta\">{meta}</p>" + (
            projector_content
            or '<p class="empty-note">No assignments logged for this week yet.</p>'
        ),
        "simulation": f"<h1>Simulation</h1><p class=\"meta\">{meta} &middot; Monte Carlo, "
        "directional not precise</p>" + simulation_content,
    }

    nav_buttons = "".join(
        f'<button class="tab-btn{" active" if i==0 else ""}" data-tab="{tab_id}">{label}</button>'
        for i, (tab_id, label) in enumerate(_TABS)
    )
    tab_sections = "".join(
        f'<section data-tabcontent="{tab_id}"{"" if i==0 else " hidden"}>{tab_bodies[tab_id]}</section>'
        for i, (tab_id, _) in enumerate(_TABS)
    )

    tab_switch_js = """
(function(){
  var buttons = document.querySelectorAll('.tab-btn');
  var contents = document.querySelectorAll('[data-tabcontent]');
  buttons.forEach(function(btn){
    btn.addEventListener('click', function(){
      buttons.forEach(function(b){ b.classList.remove('active'); });
      btn.classList.add('active');
      contents.forEach(function(c){ c.hidden = (c.dataset.tabcontent !== btn.dataset.tab); });
    });
  });
})();
"""

    body = "".join(
        [
            '<div id="app">',
            "<nav>",
            '<div class="brand"><p class="eyebrow">Office-Pool-4-Fun</p>'
            '<p class="brand-title">Strategy Console</p></div>',
            nav_buttons,
            f'<div class="nav-foot"><p class="meta" style="margin:0">{meta}<br>generated {generated_at}</p></div>',
            "</nav>",
            "<main>",
            tab_sections,
            "<footer>"
            f"<b>Confirmed &mdash; upset direction:</b> a favorite betting LOSS against a "
            f"qualifying spread counts as a 10&times; upset, same as an underdog WIN: "
            f"<b>{'yes' if cfg.upset_counts_favorite_loss else 'no'}</b> "
            f"(config-driven: upset_counts_favorite_loss).<br>"
            f"<b>Spread source for 10&times; qualification:</b> {_esc(cfg.spread_source_name)}.<br>"
            "Simulation outputs are directional, not precise &mdash; they don't know real future "
            "matchups or real competitor behavior."
            "</footer>",
            "</main>",
            "</div>",
            f"<script>{tab_switch_js}</script>",
        ]
    )

    return (
        "<!doctype html><html lang='en'><head><meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        "<title>Pool Strategy Console</title>"
        "<link rel='preconnect' href='https://fonts.googleapis.com'>"
        "<link rel='stylesheet' href='https://fonts.googleapis.com/css2?"
        "family=Big+Shoulders+Display:wght@600;700;800&family=Public+Sans:wght@400;500;600;700"
        "&family=IBM+Plex+Mono:wght@400;500;600&display=swap'>"
        f"<style>{_STYLE}</style></head><body>{body}</body></html>"
    )
